### ISSUE TITLE
Databases are fixed to two

### ISSUE THREAD

**Issue by armedi** [hyperjumptech/xcs-translator#41]
The current state of the app is based on the assumption that users will use 2 databases and that number is not configurable.

I have an idea that this database connection configuration can be put into sheetconfig.json because those configurations are very much related to each other.

It is more or less like:

```json
{
  "source": { ... },
  "destinations": [
    {
      "kind": "patient",
      "columns": {
        "inSheet": [
          { "col": "B", "name": "name" },
          { "col": "C", "name": "id_no" },
          { "col": "D", "name": "birth_date", "type": "date" },
          ...
        ],
        "outSheet": [
          { "name": "created_date" },
          { "name": "modified_date" },
          ...
        ]
      },
      "database": {
        "host": "localhost",
        "port": 3306,
        "user": "db_user",
        "password": "db_password",
        "dbName": "db_name",
        "tableName": "patient",
        "connectionLimit": 5
      }
    }
  ]
}
```

By putting database connection configuration side by side with its data source configuration, we can take out hardcoded code in a more elegant way

What do you think @haricnugraha @ilmiawan ?

**Comment by haricnugraha** [comment]
Looks like a good idea, so user only need to maintain one configuration file.

**Comment by ilmiawan** [comment]
good idea
